## Load CSV Files

#### 1)  Open a local Csv file

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv('file.csv')
df.head()

                name  age
0  neelesh ranpuriya   22
1     amit prajapati   21
2   mukul chanderiya   22
3        mayank arya   21

#### 2) Opening a csv file an URL

In [ ]:
import requests
from io import StringIO
url= 'https://github.com/NeeleshRanpuriya/Data-Science-Series/blob/main/Pandas/Datasets/kohli_ipl.csv?raw=true'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}
request = requests.get(url, headers=headers)
data = StringIO(request.text)
df = pd.read_csv('file.csv')
df.head()

                name  age
0  neelesh ranpuriya   22
1     amit prajapati   21
2   mukul chanderiya   22
3        mayank arya   21

#### 3) Step Perameter

In [ ]:
df= pd.read_csv('file.csv', sep='\t')

#### 4) Header Parameter

In [ ]:
pd.read_csv('file.csv',header=2)

     amit prajapati  21
0  mukul chanderiya  22
1       mayank arya  21

#### 5) Index Col

In [ ]:
pd.read_csv('file.csv',index_col='name')

                   age
name
neelesh ranpuriya   22
amit prajapati      21
mukul chanderiya    22
mayank arya         21

#### 6) Use Cols Parameter

In [ ]:
pd.read_csv('file.csv',usecols=['name'])

                name
0  neelesh ranpuriya
1     amit prajapati
2   mukul chanderiya
3        mayank arya

#### 7) Squeeze parameter

In [ ]:
df = pd.read_csv('file.csv')
print(df.shape)
print(df.columns)

(4, 2)
Index(['name', 'age'], dtype='object')

#### 8) Skip Rows

In [ ]:
pd.read_csv('file.csv',skiprows=2, nrows=5)

     amit prajapati  21
0  mukul chanderiya  22
1       mayank arya  21

#### 9) Encoding Prameter

In [ ]:
pd.read_csv('file.csv',encoding='utf-8')

                name  age
0  neelesh ranpuriya   22
1     amit prajapati   21
2   mukul chanderiya   22
3        mayank arya   21

#### 10) Skip bad line

In [ ]:
pd.read_csv(
    'file.csv',
    sep=',',
    on_bad_lines='skip'
)

                name  age
0  neelesh ranpuriya   22
1     amit prajapati   21
2   mukul chanderiya   22
3        mayank arya   21

#### 11) dtype parameter

In [ ]:
pd.read_csv('file.csv', dtype={'age': np.int8, 'name': 'str'})

                name  age
0  neelesh ranpuriya   22
1     amit prajapati   21
2   mukul chanderiya   22
3        mayank arya   21

#### 12) Handling Dates

In [ ]:
pd.read_csv('file.csv',parse_dates=['age'])

C:\Users\Neelesh Ranpuriya\AppData\Local\Temp\ipykernel_47316\1234490309.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv('file.csv',parse_dates=['age'])

                name age
0  neelesh ranpuriya  22
1     amit prajapati  21
2   mukul chanderiya  22
3        mayank arya  21

#### 13) Convertor

In [ ]:
pd.read_csv('file.csv',converters={'name': lambda x: x.upper()})

                name  age
0  NEELESH RANPURIYA   22
1     AMIT PRAJAPATI   21
2   MUKUL CHANDERIYA   22
3        MAYANK ARYA   21

#### 15) na_values Parameter

In [ ]:
pd.read_csv('file.csv',na_values=['NA', 'N/A', 'na', 'n/a', 'null', 'NULL','21'])

                name   age
0  neelesh ranpuriya  22.0
1     amit prajapati   NaN
2   mukul chanderiya  22.0
3        mayank arya   NaN

#### 16) Loading a huge dataset in chunks

In [ ]:
dfs=pd.read_csv('file.csv',chunksize=2)
for chunk in dfs:
    print(chunk.shape)#######fefd

(2, 2)
(2, 2)